db.url=jdbc:mysql://localhost:3306/password_vault?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=root
db.password=Asustufgamingf15

# Twilio SMS (OTP). Get from https://console.twilio.com
twilio.accountSid=AC56783adc71d3d683fa5af44554fa0afc
twilio.authToken=02a40f1821250ffe44990c982d987fcd
twilio.fromNumber=+19712880921
